spring:
  security:
    oauth2:
      client:
        registration:
          spotify:
            clientId: xxxxxxxxxxxxxxxxxxxxxx
            clientSecret: xxxxxxxxxxxxxxxxxxxxxx
            authorizationGrantType: client_credentials
        provider:
          spotify:
            tokenUri: https://accounts.spotify.com/api/token
springdoc:
  swagger-ui:
    path: /swagger-ui.html