spring:
  application:
    name: spotify-config
  cloud:
    config:
      profile: dev
      username: secure_user
      password: secure_config
  config:
    import: configserver:http://localhost:8888
  security:
    oauth2:
      client:
        registration:
          spotify:
            clientId: ${client-id}
            clientSecret: ${client-secret}
            authorizationGrantType: client_credentials
        provider:
          spotify:
            tokenUri: ${spotify.tokenUri}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
management:
  endpoints:
    web:
      exposure:
        include: "*"