spring:
  security:
    oauth2:
      client:
        registration:
          spotify:
            clientId: b1bec7cbb94b45ae9d1807fab22b0d2c
            clientSecret: bb615d8e3f564bce97001c8cc0399d9e
            authorizationGrantType: client_credentials
        provider:
          spotify:
            tokenUri: https://accounts.spotify.com/api/token
springdoc:
  swagger-ui:
    path: /swagger-ui.html